checks:
  php: true

filter:
  paths:
    - src/

build:
  environment:
    php:
      version: 8.1.18
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      dependencies:
        override:
          - wget https://sqlite.org/2021/sqlite-autoconf-3340100.tar.gz --no-check-certificate
          - tar -xvf sqlite-autoconf-3340100.tar.gz && cd sqlite-autoconf-3340100
          - CFLAGS="-O2 -DSQLITE_ENABLE_COLUMN_METADATA=1" ./configure
          - make
          - sudo make install
          - export PATH="/usr/local/lib:$PATH"
          - sqlite3 --version  && cd ..
          - composer self-update
          - composer config preferred-install.yiisoft/db source
          - composer update --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
